export const BUYOUT_STATUSES = {
  CREATED: 'CREATED',
  IN_PROGRESS: 'IN_PROGRESS',
  CHECK_PAYMENT_RETRY: 'CHECK_PAYMENT_RETRY',
  PAID: 'PAID',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  WAITING_PAYMENT: 'WAITING_PAYMENT',
  DELIVERED: 'DELIVERED',
  CHECK_PAYMENT: 'CHECK_PAYMENT',
  CANCELLED: 'CANCELLED',
  ERROR: 'ERROR'
}

export const BUYOUT_STATUSES_NAMES = {
  [BUYOUT_STATUSES.CREATED]: 'Создаётся выкуп',
  [BUYOUT_STATUSES.IN_PROGRESS]: 'Обрабатывается',
  [BUYOUT_STATUSES.WAITING_PAYMENT]: 'Ожидает оплату',
  [BUYOUT_STATUSES.CHECK_PAYMENT_RETRY]: 'Повторная проверка оплаты',
  [BUYOUT_STATUSES.PAID]: 'Оплачено',
  [BUYOUT_STATUSES.OUT_FOR_DELIVERY]: 'Отправлен',
  [BUYOUT_STATUSES.DELIVERED]: 'Доставлен',
  [BUYOUT_STATUSES.CHECK_PAYMENT]: 'Проверка оплаты',
  [BUYOUT_STATUSES.CANCELLED]: 'Отменён',
  [BUYOUT_STATUSES.ERROR]: 'Ошибка'
}

export const DELIVERY_STATUSES_NAMES = {
  [BUYOUT_STATUSES.PAID]: 'Оплачено',
  [BUYOUT_STATUSES.OUT_FOR_DELIVERY]: 'Отправлен',
  [BUYOUT_STATUSES.DELIVERED]: 'Доставлен'
}